databases:
  - name: flavor_finder
    databaseName: flavor_finder
    user: macbookpro

services:
  - type: web
    name: flavor_finder
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn flavor_finder.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flavor_finder
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4