# Generated by Django 4.2.3 on 2023-07-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_place_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
    ]
