# Generated by Django 4.2.3 on 2023-07-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_place_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="map_link",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="num_reviews",
            field=models.IntegerField(default=0),
        ),
    ]
