# Generated by Django 4.2.3 on 2023-07-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_place_map_link_alter_place_num_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="map_link",
            field=models.CharField(blank=True, null=True),
        ),
    ]
